---
- name: Setup MongoDB Secrets
  hosts: ansible_master
  gather_facts: no
  become: yes
  tasks:
    - name: Retrieve MongoDB Credentials from Secrets Manager
      aws_secretsmanager_facts:
        name: SeronSecrets
      register: secret_result

    - name: Set MongoDB Credentials as Facts
      set_fact:
        mongodb_username: "{{ secret_result.SecretString | from_json | json_query('username') }}"
        mongodb_password: "{{ secret_result.SecretString | from_json | json_query('password') }}"

